In [2]:
import os
import numpy as np 
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras.layers import Input, Conv2D, MaxPooling2D, UpSampling2D, concatenate , LeakyReLU, BatchNormalization , ReLU , Embedding , LayerNormalization, MultiHeadAttention, Add
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.models import Model
from tensorflow.keras.callbacks import EarlyStopping
# from keras.engine import Layer, InputSpec
# from tensorflow.keras.engine.topology import Layer
import keras.backend as K
import pandas as pd
import numpy as np
import ast
import cv2
# import imutils
import matplotlib.pyplot as plt
from PIL import Image

In [25]:
x = 1
y = 2 

col = tf.range(x+1)
col = tf.reshape(col, (1, -1 ))
col = tf.expand_dims(col, axis= - 1 )
row = tf.range(y+1)
row = tf.reshape(row, (-1, 1))
row = tf.expand_dims(row, axis= -1 )
print(col)
print(row)

tf.Tensor(
[[[0]
  [1]]], shape=(1, 2, 1), dtype=int32)
tf.Tensor(
[[[0]]

 [[1]]

 [[2]]], shape=(3, 1, 1), dtype=int32)


In [29]:

x_embed = tf.broadcast_to(col, shape=(tf.shape(row)[0], tf.shape(col)[1], tf.shape(row)[-1] ))
x_embed

<tf.Tensor: shape=(3, 2, 1), dtype=int32, numpy=
array([[[0],
        [1]],

       [[0],
        [1]],

       [[0],
        [1]]])>

In [33]:
y_embed = tf.broadcast_to(row , shape=(tf.shape(row)[0], tf.shape(col)[1],  tf.shape(row)[-1] ))
y_embed

<tf.Tensor: shape=(3, 2, 1), dtype=int32, numpy=
array([[[0],
        [0]],

       [[1],
        [1]],

       [[2],
        [2]]])>

In [36]:
pos = tf.concat([y_embed,  x_embed], axis= -1 )
pos.numpy()

array([[[0, 0],
        [0, 1]],

       [[1, 0],
        [1, 1]],

       [[2, 0],
        [2, 1]]])

In [7]:
x = 1 
y = 2 


x = tf.cast(x, dtype='int32')
y = tf.cast(y, dtype='int32')
# print(f'row :{row}')
# print(f'col: {col}')
col = tf.range(x+1)
row = tf.range(y+1)

In [13]:
x_embedding = Embedding(input_dim = 30, output_dim = 256)(col)
y_embedding = Embedding(input_dim = 30, output_dim = 256)(row)
print(x_embedding.shape)
print(y_embedding.shape)


(2, 256)
(3, 256)


In [14]:
x_embedding = tf.expand_dims(x_embedding,axis=0)
y_embedding = tf.expand_dims(y_embedding,axis=1)

print(x_embedding.shape)
print(y_embedding.shape)



(1, 2, 256)
(3, 1, 256)


In [15]:
x_embedding =tf.broadcast_to(x_embedding,(tf.shape(y_embedding)[0], tf.shape(x_embedding)[1], tf.shape(x_embedding)[2]))
y_embedding = tf.broadcast_to(y_embedding, (tf.shape(y_embedding)[0], tf.shape(x_embedding)[1], tf.shape(y_embedding)[2]))


print(x_embedding.shape)
print(y_embedding.shape)

(3, 2, 256)
(3, 2, 256)


In [16]:
pos_ = tf.concat([y_embedding, x_embedding], axis= -1)
pos_

<tf.Tensor: shape=(3, 2, 512), dtype=float32, numpy=
array([[[-0.02529458,  0.00918697,  0.04567603, ...,  0.00144196,
          0.01159276, -0.02566282],
        [-0.02529458,  0.00918697,  0.04567603, ..., -0.01958464,
         -0.00228348, -0.00463637]],

       [[-0.03309761, -0.04748386,  0.04459962, ...,  0.00144196,
          0.01159276, -0.02566282],
        [-0.03309761, -0.04748386,  0.04459962, ..., -0.01958464,
         -0.00228348, -0.00463637]],

       [[ 0.02397679, -0.01928424, -0.00918525, ...,  0.00144196,
          0.01159276, -0.02566282],
        [ 0.02397679, -0.01928424, -0.00918525, ..., -0.01958464,
         -0.00228348, -0.00463637]]], dtype=float32)>